### ISSUE TITLE
artifacts_folder in playwright-pytest is now a fixture

### ISSUE THREAD

**Issue by m-reichle** [m9810223/playwright-async-pytest#7]
Hi,

playwright-pytest have migrated the artifacts folder into a fixture in https://github.com/microsoft/playwright-pytest/pull/223. Because of this the import in https://github.com/m9810223/playwright-async-pytest/blob/master/src/pytest_playwright_async/__init__.py#L17 is now broken and playwright-async-pytest isn't running with the current version of playwright-pytest.

**Comment by m-reichle** [comment]
Thanks for the super fast fix!!

**Comment by m9810223** [comment]
Please use `pytest_playwright_async>=0.16.0` for `pytest-playwright>=0.5.0`!
